name: paa-unit-tests-and-quality-workflow
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
jobs:
  unit-tests-and-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies for tests
        run: |
          pip install --upgrade pip
          pip install ".[tests]"
      - name: Run tests and coverage
        run: |
          pytest --cov
      - name: Code Quality
        run: | 
          flake8 --ignore E501 paa
          black paa
